version: '3'
services:
  mongo:
    container_name: message_mongodb
    image: mongo:latest
    networks:
      - gateway
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db
  node:
    container_name: message_node
    restart: always
    build: .
    networks:
      - gateway
    ports:
      - 3002:3002
    volumes:
      - .:/usr/src/app
    environment:
      MONGODB_URL: mongodb://mongo:27017/minichat-message-MS
      PORT: 3002
      JWT_SECRET: somesecrets
      SERVER_PORT: 3001
      YOUR_DOMAIN: http://localhost:3002

    links:
      - mongo
    depends_on:
      - mongo

volumes:
  mongo: {}
networks:
  gateway: {}